# Generated by Django 4.2.6 on 2023-10-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(verbose_name='Текст на главной страницеи')),
            ],
        ),
    ]
